name: CI/CD to GCP Cloud Run

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Authenticate Docker with Artifact Registry (Jakarta)
      run: |
        gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/exercise-2/exercise-2 .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/exercise-2/exercise-2

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy exercise-2 \
          --image asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/exercise-2/exercise-2 \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated
