name: CI/CD to GCP Cloud Run

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode GCP credentials
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > "${{ github.workspace }}/key.json"

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ github.workspace }}/key.json
        export_default_credentials: true

    - name: Configure Docker to use gcloud
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/exercise-2 .

    - name: Push Docker image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/exercise-2

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy exercise-2 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/exercise-2 \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
