name: Build and Push Docker to Artifact Registry

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode GCP credentials to key.json
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 -d > "${HOME}/key.json"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth activate-service-account --key-file="${HOME}/key.json"
          gcloud config set project github-actions-deployer-463016
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/github-actions-deployer-463016/exercise-2/exercise-2 .

      - name: Push Docker image
        run: |
          docker push asia-southeast2-docker.pkg.dev/github-actions-deployer-463016/exercise-2/exercise-2
