name: Deploy Flask App

on:
  push:
    branches: [main]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t flask-todo-app .

      - name: Run container (for testing only)
        run: docker run -d -p 5000:5000 flask-todo-app

      
